DEBUG 2021-06-15 08:40:46.997 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-15 08:40:46.997 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-15 08:40:46.998 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-15 08:40:46.998 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
INFO 2021-06-15 08:40:46.999 UTC: 	 Will use CRAB configuration file configs/ttjets_cfg.py
DEBUG 2021-06-15 08:40:46.999 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-15 08:40:47.001 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-15 08:40:47.001 UTC: 	 Working area '/afs/cern.ch/work/m/melu/work/CMSSW_10_2_26/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_ttJets' already exists 
Please change the requestName in the config file
ERROR 2021-06-15 08:40:47.002 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.00/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/melu/work/CMSSW_10_2_26/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_ttJets' already exists 
Please change the requestName in the config file
INFO 2021-06-15 08:40:47.006 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_2_26/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
